# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # ou main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (Passos Checkout, Install Node.js, Install dependencies) ...

      - name: Debug Passed Environment Variables # NOVO PASSO TEMPORÁRIO PARA DEBUG
        run: |
          echo "VITE_FIREBASE_API_KEY is: ${{ env.VITE_FIREBASE_API_KEY }}"
          echo "VITE_FIREBASE_PROJECT_ID is: ${{ env.VITE_FIREBASE_PROJECT_ID }}"
          # Adicione mais variáveis aqui para verificar todas
        env: # Este 'env' define variáveis de ambiente para este passo específico
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }} # Opcional

      - name: Build project # Seu passo de build existente
        run: npm run build
        env: # ESTE 'env' também precisa estar aqui para o passo de build
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}